include: package:lints/recommended.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - test/**/*.g.dart

linter:
  rules:
    always_use_package_imports: true
    library_private_types_in_public_api: true
    prefer_single_quotes: true
    sort_pub_dependencies: true
    type_annotate_public_apis: true
