include: package:lints/recommended.yaml

linter:
  rules:
    always_use_package_imports: true
    library_private_types_in_public_api: true
    sort_pub_dependencies: true
    type_annotate_public_apis: true
