name: spotify_api
version: 0.5.1-alpha
homepage: https://github.com/BjoernPetersen/spotify_api
description: A wrapper for the Spotify Web API, implemented in Dart.

environment:
  sdk: ^3.0.0

dependencies:
  convert: ^3.0.0
  http: ^1.0.0
  json_annotation: ^4.8.1
  logger: ^2.0.0
  meta: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  dotenv: ^4.0.0
  file: ^7.0.0
  file_testing: ^3.0.0
  json_serializable: ^6.0.0
  lints: ^2.0.0
  sane_uuid: ^1.0.0-alpha.4
  shelf: ^1.4.0
  test: ^1.0.0
