name: spotify_api
version: 0.1.0

environment:
  sdk: ^2.16.0

dependencies:
  convert: ^3.0.0
  http: ^0.13.4
  json_annotation: ^4.4.0
  logger: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  dotenv: ^4.0.0
  json_serializable: ^6.0.0
  lints: ^1.0.0
  meta: ^1.0.0
  test: ^1.0.0
