name: Workflow
on:
  push:
    branches:
      - 'main'
  pull_request:


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: dart:2.18
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Get dependencies
        run: dart pub get
      - name: Run code generation
        run: dart run build_runner build
      - name: Run tests
        run: dart test

  check_format:
    name: Check Format
    runs-on: ubuntu-latest
    container: dart:2.18
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Check lib formatting
        run: dart format lib --set-exit-if-changed
      - name: Check test formatting
        run: dart format test --set-exit-if-changed
      - name: Check example formatting
        run: dart format example --set-exit-if-changed

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: dart:2.18
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Get dependencies
        run: dart pub get
      - name: Run code generation
        run: dart run build_runner build
      - name: Run Analysis
        run: dart analyze --fatal-infos
