name: Workflow
on:
  push:
    branches:
      - 'main'
  pull_request:


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: dart:2.18
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Get dependencies
        run: dart pub get
      - name: Run code generation
        run: dart run build_runner build
      - name: Run tests
        run: dart test --file-reporter json:test-results.json --coverage=.coverage
      - name: Upload test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Unit Test Results
          path: test-results.json
          reporter: dart-json
      - name: Install coverage package
        run: dart pub global activate coverage
      - name: Convert to LCOV
        run: dart pub global run coverage:format_coverage --report-on=lib --lcov -o ./.coverage/lcov.info -i ./.coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: .coverage/lcov.info

  integration_test:
    name: Integration Tests
    runs-on: ubuntu-latest
    container: dart:2.18
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Get dependencies
        run: dart pub get
      - name: Run code generation
        run: dart run build_runner build
      - name: Run tests
        run: dart test -P integration --file-reporter json:test-results.json --coverage=.coverage
        env:
          CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
      - name: Upload test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Integration Test Results
          path: test-results.json
          reporter: dart-json
      - name: Install coverage package
        run: dart pub global activate coverage
      - name: Convert to LCOV
        run: dart pub global run coverage:format_coverage --report-on=lib --lcov -o ./.coverage/lcov.info -i ./.coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: .coverage/lcov.info

  check_format:
    name: Check Format
    runs-on: ubuntu-latest
    container: dart:2.18
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Check lib formatting
        run: dart format lib --set-exit-if-changed
      - name: Check test formatting
        run: dart format test --set-exit-if-changed
      - name: Check example formatting
        run: dart format example --set-exit-if-changed

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: dart:2.18
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Get dependencies
        run: dart pub get
      - name: Run code generation
        run: dart run build_runner build
      - name: Run Analysis
        run: dart analyze --fatal-infos
